/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.formdev.flatlaf.FlatDarculaLaf;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author angel_p11
 */
public class GameOfLife extends javax.swing.JFrame {
    private final ImageIcon icon = new ImageIcon(getClass().getResource("/Images/icon.png"));

    /**
     * Creates new form GameOfLife
     */
    public GameOfLife() {
        initComponents();
        super.setLocationRelativeTo(null);
        super.setIconImage(icon.getImage());
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container = new javax.swing.JPanel();
        boardContainer = new javax.swing.JPanel();
        footerContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game of Life");
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        container.setMinimumSize(new java.awt.Dimension(720, 512));
        container.setLayout(new java.awt.GridBagLayout());

        boardContainer.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        boardContainer.setMinimumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout boardContainerLayout = new javax.swing.GroupLayout(boardContainer);
        boardContainer.setLayout(boardContainerLayout);
        boardContainerLayout.setHorizontalGroup(
            boardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardContainerLayout.setVerticalGroup(
            boardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.9;
        container.add(boardContainer, gridBagConstraints);

        footerContainer.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout footerContainerLayout = new javax.swing.GroupLayout(footerContainer);
        footerContainer.setLayout(footerContainerLayout);
        footerContainerLayout.setHorizontalGroup(
            footerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        footerContainerLayout.setVerticalGroup(
            footerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        container.add(footerContainer, gridBagConstraints);

        getContentPane().add(container, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch (UnsupportedLookAndFeelException e) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GameOfLife().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boardContainer;
    private javax.swing.JPanel container;
    private javax.swing.JPanel footerContainer;
    // End of variables declaration//GEN-END:variables
}
